version: '3.1'

services:

  db:
    image: mysql:8.0
    container_name: booksshop
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: shop_db
      MYSQL_USER: shop-dev
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: example