spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://shop-dev:root@localhost:3306/shop_db'
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: 'jdbc:mysql://shop-dev:root@localhost:3306/shop_db'